# Generated by Django 4.1.3 on 2022-11-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
