# Generated by Django 4.1.3 on 2022-11-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_code',
        ),
    ]
