# Generated by Django 4.1.3 on 2022-11-26 11:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, choices=[('1', 'Аламединская 1'), ('38', '38 Гимназия'), ('Айчурок', 'Айчурок'), ('61', '61 школа'), ('67', '67 школа гимназия')], max_length=100, null=True)),
                ('students_inn', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('guardians_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardians_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('guardians_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('guardians_inn', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('characteristic', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students_image')),
                ('inn', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('nation', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(blank=True, max_length=10, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('inn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.counselor')),
            ],
        ),
    ]
