# Generated by Django 4.1.3 on 2022-11-26 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('students_inn', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('guardians_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardians_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('guardians_number', models.IntegerField(blank=True, null=True)),
                ('guardians_inn', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('characteristic', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('nation', models.CharField(blank=True, max_length=20, null=True)),
                ('counselors_inn', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('student_class', models.CharField(blank=True, max_length=10, null=True)),
                ('quarters_1_grade', models.IntegerField(blank=True, null=True)),
                ('quarters_2_grade', models.IntegerField(blank=True, null=True)),
                ('quarters_3_grade', models.IntegerField(blank=True, null=True)),
                ('quarters_4_grade', models.IntegerField(blank=True, null=True)),
                ('years_grade', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school_name', to='school.school')),
                ('users_inn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_inn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
