# Generated by Django 4.1.3 on 2022-11-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='school_name',
            field=models.ForeignKey(blank=True, choices=[('1', 'Аламединская 1'), ('38', '38 Гимназия'), ('Айчурок', 'Айчурок'), ('61', '61 школа'), ('67', '67 школа гимназия')], null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school_name', to='school.school'),
        ),
    ]
