# Generated by Django 4.1.3 on 2022-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_studentdocument_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='school_name',
            field=models.CharField(blank=True, choices=[('1', 'Аламединская 1'), ('38', '38 Гимназия'), ('Айчурок', 'Айчурок'), ('61', '61 школа'), ('67', '67 школа гимназия')], max_length=255, null=True),
        ),
    ]
