# Generated by Django 4.1.3 on 2022-11-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='users_inn',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
