# Generated by Django 4.1.3 on 2022-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_delete_counselor_studentdocument_characteristic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdocument',
            old_name='grade',
            new_name='quarters_1_grade',
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='quarters_2_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='quarters_3_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='quarters_4_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='years_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
