# Generated by Django 4.1.3 on 2022-11-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_studentdocument_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='counselors_inn',
        ),
    ]
