# Generated by Django 4.1.3 on 2022-11-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_students_users_reset_code'),
        ('documents', '0003_rename_grade_studentdocument_quarters_1_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='counselors_inn',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='guardians_inn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='guardians_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='guardians_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='guardians_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='nation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='quarters_1_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='quarters_2_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='quarters_3_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='quarters_4_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='school_name',
            field=models.CharField(blank=True, choices=[('1', 'Аламединская 1'), ('38', '38 Гимназия'), ('Айчурок', 'Айчурок'), ('61', '61 школа'), ('67', '67 школа гимназия')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='student_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='students_inn',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='surname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='users_inn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.students'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='years_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
